[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
web3register = "7MReDm6FiS3n4A1sxTxdHu8p92TQutQSws715azLqtYj"

[programs.devnet]
web3register = "7MReDm6FiS3n4A1sxTxdHu8p92TQutQSws715azLqtYj"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "http://localhost:8899"
wallet = "/home/f/wallet/test1.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

