[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
web3 = "5UCAW1GRyMK6gcMwhZmaG3fWb5ocsXBBm6W9DdYuyiVL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/home/f/wallet/left-solana-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
